networks:
  inception:
  
services:
  mariadb:
    image: "i-mariadb:1.0.0"
    env_file:
      - .env
    build: ./requirements/mariadb 
    volumes:
      - mariadb_data:/data/
    networks:
      - inception
   wordpress:
    image: "i_wordpress:1.0.0"
    build: 
       - ./requirements/wordpress
    volumes:
       - wordpress_data:/var/www/html
    env_file:
       - .env
    networks:
       - inception
   nginx:
    image: "i-nginx:1.0.0"
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/htmp/
    networks:
      - inception


volumes:
