networks:
  mariadb

services:

  mariadb:
    image: i-mariadb:1.0.0
    env_file:
      - .env
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/data/
    networks:
      - backend